CREATE TABLE ROOM(
    ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CAPACITY INT NOT NULL,
    FLOOR INT
 NOT NULL);

CREATE TABLE GUEST(
    ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(50),
    CREDITCARD VARCHAR(50)
);

CREATE TABLE ACCOMODATION(
    ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    GUESTID INTEGER NOT NULL,
    ROOMID INTEGER NOT NULL,
    STARTDATE DATE,
    ENDDATE DATE
)


