-- schema-database.sql

DROP TABLE ROOM;
DROP TABLE GUEST;
DROP TABLE ACCOMODATION;
CREATE TABLE ROOM(
    ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ROOMNUMBER INT,
    CAPACITY INT,
    FLOOR INT
);

CREATE TABLE GUEST(
    ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(50),
    CREDITCARD VARCHAR(50)
);

CREATE TABLE ACCOMODATION(
    ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    GUESTID INTEGER NOT NULL,
    ROOMID INTEGER NOT NULL,
    STARTDATE DATE,
    ENDDATE DATE
);

INSERT INTO ROOM(ROOMNUMBER,CAPACITY,FLOOR) VALUES(2,10,5);
INSERT INTO ROOM(ROOMNUMBER,CAPACITY,FLOOR) VALUES(4,50,6);
INSERT INTO GUEST(NAME, CREDITCARD) VALUES('PAVEL','1234');
INSERT INTO GUEST(NAME, CREDITCARD) VALUES('JAN','57895');




